name: .NET CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore Dependencies
      run: dotnet restore ./Ch07/TicTacToe.sln
    - name: Build
      run: dotnet build ./Ch07/TicTacToe.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./Ch07/TicTacToe.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory "./Ch07/TestResults-${{ matrix.dotnet-version }}"
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ./Ch07/TestResults-${{ matrix.dotnet-version }}/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
    - name: Add Coverage Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
